### ISSUE TITLE
Cannot use GraphQLInputObjectType \"UsersFilters\" from another module or realm

### ISSUE THREAD

**Issue by oney** [drizzle-team/drizzle-graphql#16] opened 2024-06-23 06:58 UTC
I create my nextjs app with `npm create t3-app@latest`. And then add file in `src/app/api/graphql/route.ts` with
```typescript
import { buildSchema } from "drizzle-graphql";
import { startServerAndCreateNextHandler } from "@as-integrations/next";
import { ApolloServer } from "@apollo/server";
import { NextRequest } from "next/server";
import { gql } from "graphql-tag";
import { db } from "~/server/db";

const { schema } = buildSchema(db);

const server = new ApolloServer({
  schema,
});

const handler = startServerAndCreateNextHandler<NextRequest>(server, {
  context: async (req) => ({ req }),
});

export { handler as GET, handler as POST };
```
And in `http://localhost:3000/api/graphql` I got an error when sending a query with input (no input is fine)
```
{
  "errors": [
    {
      "message": "Cannot use GraphQLInputObjectType \"UsersFilters\" from another module or realm.\n\nEnsure that there is only one instance of \"graphql\" in the node_modules\ndirectory. If different versions of \"graphql\" are the dependencies of other\nrelied on modules, use \"resolutions\" to ensure only one version is installed.\n\nhttps://yarnpkg.com/en/docs/selective-version-resolutions\n\nDuplicate \"graphql\" modules cannot be used at the same time since different\nversions may have different capabilities and behavior. The data from one\nversion used in the function from another could produce confusing and\nspurious results.",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "users"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "stacktrace": [
          "GraphQLError: Cannot use GraphQLInputObjectType \"UsersFilters\" from another module or realm.",
          "",
          "Ensure that there is only one instance of \"graphql\" in the node_modules",
          "directory. If different versions of \"graphql\" are the dependencies of other",
          "relied on modules, use \"resolutions\" to ensure only one version is installed.",
          "",
          "https://yarnpkg.com/en/docs/selective-version-resolutions",
          "",
          "Duplicate \"graphql\" modules cannot be used at the same time since different",
          "versions may have different capabilities and behavior. The data from one",
          "version used in the function from another could produce confusing and",
          "spurious results.",
          "    at resolver (webpack-internal:///(rsc)/./node_modules/drizzle-graphql/index.js:1417:17)",
          "    at field.resolve (webpack-internal:///(rsc)/./node_modules/@apollo/server/dist/esm/utils/schemaInstrumentation.js:46:28)",
          "    at executeField (webpack-internal:///(rsc)/./node_modules/graphql/execution/execute.mjs:477:20)",
          "    at executeFields (webpack-internal:///(rsc)/./node_modules/graphql/execution/execute.mjs:409:20)",
          "    at executeOperation (webpack-internal:///(rsc)/./node_modules/graphql/execution/execute.mjs:340:14)",
          "    at execute (webpack-internal:///(rsc)/./node_modules/graphql/execution/execute.mjs:134:20)",
          "    at executeIncrementally (webpack-internal:///(rsc)/./node_modules/@apollo/server/dist/esm/incrementalDeliveryPolyfill.js:26:60)",
          "    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)",
          "    at async execute (webpack-internal:///(rsc)/./node_modules/@apollo/server/dist/esm/requestPipeline.js:249:37)",
          "    at async processGraphQLRequest (webpack-internal:///(rsc)/./node_modules/@apollo/server/dist/esm/requestPipeline.js:178:32)",
          "    at async internalExecuteOperation (webpack-internal:///(rsc)/./node_modules/@apollo/server/dist/esm/ApolloServer.js:637:16)",
          "    at async runHttpQuery (webpack-internal:///(rsc)/./node_modules/@apollo/server/dist/esm/runHttpQuery.js:141:29)",
          "    at async runPotentiallyBatchedHttpQuery (webpack-internal:///(rsc)/./node_modules/@apollo/server/dist/esm/httpBatching.js:40:16)",
          "    at async ApolloServer.executeHTTPGraphQLRequest (webpack-internal:///(rsc)/./node_modules/@apollo/server/dist/esm/ApolloServer.js:548:20)"
        ]
      }
    }
  ]
}
```

I try the raw Apollo server like the following and there is no error
```typescript
const typeDefs = gql`
  input World {
    world: String
  }
  type Query {
    hello(world: World): String
  }
`;

const resolvers = {
  Query: {
    hello: () => "Hello world!",
  },
};

const server = new ApolloServer({
  typeDefs,
  resolvers,
});
```

Let me know if you need more info to reproduce it

**Comment by Sukairo-02** [comment] 2024-06-23 11:56
I've actually encountered that issue with tests, it was resolved by adding 
```Typescript
resolve: { alias: { graphql: 'graphql/index.js' } }
```
to vitest config, maybe that will help you somehow, but I'll investigate the issue regardless, thanks for submitting.

**Comment by Sukairo-02** [comment] 2024-06-26 09:32
Well, I've tried to reproduce it several times, and don't seem to have any issues, perhaps your packages are broken and there are indeed several different versions of GraphQL present and active at the same time.

**Comment by Sukairo-02** [comment] 2024-08-19 12:25
Well, this issue has been here for a while, and, as I'm unable to reproduce it, I'll close it till I get extra information allowing me to actually encounter it.

**Closed by Sukairo-02** 2024-08-19 12:25 UTC
